import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import NavbarWrapper from "@/components/navbar-wrapper"; // Wrapper for Navbar
import FooterWrapper from "@/components/footer-wrapper"; // Wrapper for Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarWrapper /> {/* Client-side logic for Navbar */}
        {children}
        <FooterWrapper /> {/* Client-side logic for Footer */}
      </body>
    </html>
  );
}
